### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by C4ptainCrunch**

### CODE REVIEW

**Comment by aantuness** [comment]
Coomit id:  6cbf978 
Errors out once you run in the dockerfile lechbot.py, commented it out to pass tests

Traceback below:
  
  ERROR 2021-04-24 15:07:49,026 | base_events:default_exception_handler | Exception in callback BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)
handle: <Handle BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/usr/local/lib/python3.9/selectors.py", line 360, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted

**Comment by C4ptainCrunch** [comment]
@titouanc : l'erreur de @aantuness est due au fait qu'on run lechbot.py --debug par défaut et que lechbot essaie de se binder à stdin (fd 0) et il ne peut pas (why ?) et ça donne "KeyError: '0 is not registered'"

**Comment by titouanc** [comment]
Par défaut, si on lance `python lechbot.py` sans argument, il lance le backend cli. Je pense que `docker-compose up` lance les containers sans stdin (/dev/null), qui produit la même erreur:
```
python lechbot.py -l < /dev/null 
   INFO 2021-04-24 20:53:50,828 | abstractbot:connect | Connected !
   INFO 2021-04-24 20:53:50,828 | lechbot:main | Starting
   INFO 2021-04-24 20:53:50,828 | lechbot:main | You are in local mode, we will not try to poll from twitter, the incubator or any other distant api.
>>> RUNNING IN COMMAND LINE MODE ONLY <<<
  ERROR 2021-04-24 20:53:50,829 | base_events:default_exception_handler | Exception in callback BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)
handle: <Handle BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.7/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 259, in _add_reader
    (handle, None))
  File "/usr/lib/python3.7/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted
^CTraceback (most recent call last):
  File "lechbot.py", line 71, in <module>
    main(lvl, klass, options)
  File "lechbot.py", line 33, in main
    asyncio.get_event_loop().run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
  ERROR 2021-04-24 20:53:52,081 | base_events:default_exception_handler | Task was destroyed but it is pending!
task: <Task pending coro=<CLIBot.stdin_mainloop() running at /home/titou/Urlab/lechbot/ircbot/clibot.py:68> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff7d8e3f5d0>()]>>
```

La solution est de lancer `python lechbot.py --irc`

**Comment by aantuness** [comment]
python lechbot.py --irc dans le docker:

Building lechbot
Sending build context to Docker daemon  5.873MB
Step 1/6 : FROM python:3.9-buster
 ---> 49e3c70d884f
Step 2/6 : WORKDIR /home/lechbot/test
 ---> Using cache
 ---> 1d016fc78f9f
Step 3/6 : COPY requirements.txt .
 ---> Using cache
 ---> 9b1d7815f532
Step 4/6 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> dc05d42a6e4c
Step 5/6 : COPY . .
 ---> Using cache
 ---> e10745dd8af1
Step 6/6 : RUN python lechbot.py --irc
 ---> Running in 13bff2bba681
Cannot load local config; using gitted config
   INFO 2021-04-24 20:47:57,365 | irc:connection_made | Connection success.
   INFO 2021-04-24 20:48:01,368 | ircbot:_connect | Connected to chat.freenode.net
   INFO 2021-04-24 20:48:01,368 | abstractbot:connect | Connected !
   INFO 2021-04-24 20:48:01,369 | lechbot:main | Starting
  ERROR 2021-04-24 20:48:01,371 | base_events:default_exception_handler | Exception in callback IRCProtocol._register()
handle: <TimerHandle when=8789.262188218 IRCProtocol._register()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/asyncirc/irc.py", line 169, in _register
    signal("registration-complete").send(self)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/cap.py", line 23, in registration_complete
    request_capabilities(client, capabilities_available[client.netid] & capabilities_requested[client.netid])
KeyError: '118826625974960:chat.freenode.net:6697+'
  ERROR 2021-04-24 20:48:01,506 | base_events:default_exception_handler | application protocol failed to receive SSL data
protocol: <asyncio.sslproto.SSLProtocol object at 0x6c127ad91460>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 545, in data_received
    self._app_protocol.data_received(chunk)
  File "/usr/local/lib/python3.9/site-packages/asyncirc/irc.py", line 102, in data_received
    signal("raw").send(self, text=line_received)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/core.py", line 115, in _redispatch_raw
    signal("irc").send(message)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/core.py", line 110, in _redispatch_irc
    signal("irc-{}".format(message.verb.lower())).send(message)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/cap.py", line 62, in handle_irc_cap
    request_capabilities(message.client, capabilities_available[message.client.netid] & capabilities_requested[message.client.netid])
KeyError: '118826625974960:chat.freenode.net:6697+'
CRITICAL 2021-04-24 20:48:01,507 | irc:connection_lost | Connection lost.
CRITICAL 2021-04-24 20:48:01,507 | irc:disconnected | Disconnected from 118826625974960:chat.freenode.net:6697+. Attempting to reconnect...
   INFO 2021-04-24 20:48:01,901 | irc:connection_made | Connection success.
CRITICAL 2021-04-24 20:48:01,901 | irc:reconnected | Reconnected! 118826625974960:chat.freenode.net:6697+
  ERROR 2021-04-24 20:48:02,902 | base_events:default_exception_handler | Exception in callback IRCProtocol._register()
handle: <TimerHandle when=8793.797615724 IRCProtocol._register()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/asyncirc/irc.py", line 169, in _register
    signal("registration-complete").send(self)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/cap.py", line 23, in registration_complete
    request_capabilities(client, capabilities_available[client.netid] & capabilities_requested[client.netid])
KeyError: '118826625974960:chat.freenode.net:6697+'
  ERROR 2021-04-24 20:48:03,529 | base_events:default_exception_handler | application protocol failed to receive SSL data
protocol: <asyncio.sslproto.SSLProtocol object at 0x6c127ad91c40>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 545, in data_received
    self._app_protocol.data_received(chunk)
  File "/usr/local/lib/python3.9/site-packages/asyncirc/irc.py", line 102, in data_received
    signal("raw").send(self, text=line_received)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/core.py", line 115, in _redispatch_raw
    signal("irc").send(message)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/core.py", line 110, in _redispatch_irc
    signal("irc-{}".format(message.verb.lower())).send(message)
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/asyncirc/plugins/cap.py", line 62, in handle_irc_cap
    request_capabilities(message.client, capabilities_available[message.client.netid] & capabilities_requested[message.client.netid])
KeyError: '118826625974960:chat.freenode.net:6697+'
CRITICAL 2021-04-24 20:48:03,529 | irc:connection_lost | Connection lost.
CRITICAL 2021-04-24 20:48:03,529 | irc:disconnected | Disconnected from 118826625974960:chat.freenode.net:6697+. Attempting to reconnect...

**Comment by C4ptainCrunch** [comment]
Closed by c65e1666d0f8f866cf01b6d36513a96ce4b02644 for now

**Pull request closed without merging**
